version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - regretbox

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
    networks:
      - regretbox

volumes:
  redis_data:

networks:
  regretbox:
    driver: bridge
