version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - regretbox
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - REDIS_URL=redis:6379
      - PORT=8080
    depends_on:
      - redis
    networks:
      - regretbox
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis_data:

networks:
  regretbox:
    driver: bridge
